#!/bin/bash

# Pull down private dotfiles
git submodule init
git submodule update --recursive

# TODO: Add backup functionality

# Join private and public dotfiles
cat ${PWD}/bash/.bashrc ${PWD}/dotfiles-private/bash/.bashrc > ~/.bashrc
